name: Production Workflow

on:
  workflow_run:
    workflows: ["ESLint"]
    types:
      - completed
    branches:
      - main

jobs:
  frontend-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Start frontend server
        run: |
          cd frontend
          npm start &
          sleep 10  # Give the server some time to start

      - name: Test frontend
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
          if [ $response = "200" ]; then
            echo "Frontend is working correctly"
            exit 0
          else
            echo "Frontend is not working. HTTP status code: $response"
            exit 1
          fi

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd backend
          npm ci
      
      - name: Test backend
        run: |
          cd backend
          npm run start
      - name: Test Backend
        run: |
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
            if [ $response = "200" ]; then
              echo "Backend is working correctly"
              exit 0
            else
              echo "Backend is not working. HTTP status code: $response"
              exit 1
            fi

  deploy:
    needs: [frontend-test, backend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
         
